# Generated by Django 4.2.7 on 2026-01-22 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outfits', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outfit',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='outfit',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='outfit',
            name='category',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('dress', 'Dress'), ('full_outfit', 'Full Outfit')], default='full_outfit', max_length=20),
        ),
        migrations.AddField(
            model_name='outfit',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='outfit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outfit',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outfit',
            name='occasion',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('formal', 'Formal'), ('sports', 'Sports'), ('party', 'Party'), ('work', 'Work')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='outfit_shoulder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('all_season', 'All Season')], max_length=20),
        ),
        migrations.AddField(
            model_name='outfit',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='outfits/thumbnails/'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='times_worn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outfit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_colors', models.JSONField(blank=True, default=list)),
                ('preferred_brands', models.JSONField(blank=True, default=list)),
                ('preferred_styles', models.JSONField(blank=True, default=list)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutfitTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='outfits.outfit')),
            ],
            options={
                'unique_together': {('outfit', 'tag')},
            },
        ),
    ]
